// <auto-generated />
namespace Booker.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AccountModel_4C7A657E05C84C4692ABA6F795DB4556 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountModel_4C7A657E05C84C4692ABA6F795DB4556));
        
        string IMigrationMetadata.Id
        {
            get { return "201707301801490_AccountModel_4C7A657E05C84C4692ABA6F795DB4556"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
