// <auto-generated />
namespace Booker.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstMigration_EB5D96B6B1934F87901F2831E8A43E21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstMigration_EB5D96B6B1934F87901F2831E8A43E21));
        
        string IMigrationMetadata.Id
        {
            get { return "201707181758394_FirstMigration_EB5D96B6B1934F87901F2831E8A43E21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
